### ISSUE TITLE
[Bug] legends, scalebar, north arrow, and text fail on 7.8.5

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#1244]
**Describe the bug**
None of the map additions (legends, scale, north arrow, text) work in the new 7..8.5 version. They all raise similar errors in the console. Here is an example:

```
Traceback (most recent call last):
  File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w
xpython/core/gthread.py", line 137, in OnDone

event.ondone(event)
  File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w
xpython/core/render.py", line 479, in OnRenderDone

self.updateProgress.emit(env=event.userdata['env'],
layer=self.layer)
  File "/Applications/GRASS-7.8.app/Contents/Resources/etc/p
ython/grass/pydispatch/signal.py", line 229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "/Applications/GRASS-7.8.app/Contents/Resources/etc/p
ython/grass/pydispatch/dispatcher.py", line 344, in send

response = robustapply.robustApply(
  File "/Applications/GRASS-7.8.app/Contents/Resources/etc/p
ython/grass/pydispatch/robustapply.py", line 60, in
robustApply

return receiver(*arguments, **named)
  File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w
xpython/core/render.py", line 774, in ReportProgress

self.renderDone.emit(env=env)
  File "/Applications/GRASS-7.8.app/Contents/Resources/etc/p
ython/grass/pydispatch/signal.py", line 229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "/Applications/GRASS-7.8.app/Contents/Resources/etc/p
ython/grass/pydispatch/dispatcher.py", line 344, in send

response = robustapply.robustApply(
  File "/Applications/GRASS-7.8.app/Contents/Resources/etc/p
ython/grass/pydispatch/robustapply.py", line 60, in
robustApply

return receiver(*arguments, **named)
  File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w
xpython/mapwin/buffered.py", line 961, in _updateMFinished

for img in self.GetOverlay():
  File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w
xpython/mapwin/buffered.py", line 785, in GetOverlay

img = utils.autoCropImageFromFile(overlay.mapfile)
  File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w
xpython/core/utils.py", line 1098, in autoCropImageFromFile

return PilImageToWxImage(cropped, copyAlpha=True)
  File "/Applications/GRASS-7.8.app/Contents/Resources/gui/w
xpython/core/utils.py", line 1051, in PilImageToWxImage

getattr(
AttributeError
:
'Image' object has no attribute 'tostring'
```

**System description (please complete the following information):**

- Operating System: MacOS 11.1
- GRASS GIS version 7.8.5 stable
- details about further software components
version=7.8.5
date=2020
revision=exported
build_date=2021-01-11
build_platform=x86_64-apple-darwin20.2.0
build_off_t_size=8
libgis_revision=2021-01-11T17:09:27+00:00
libgis_date=2021-01-11T17:09:27+00:00
proj=7.1.1
gdal=3.1.4
geos=3.8.1
sqlite=3.33.0

python3 -c "import sys, wx; print(sys.version); print(wx.version())"
3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 19:17:44)
[Clang 11.0.0 ]
4.0.7.post2 osx-cocoa (phoenix) wxWidgets 3.0.5
GRASS 7.8.5 (nc_spm_08_grass7)

**Comment by cmbarton** [comment]
These tools ARE working in version 7.9 dev.

**Comment by petrasovaa** [comment]
Addressed in #1223.

**Comment by cmbarton** [comment]
Thanks. I'll look at that one. I did a search and didn't see anything.
