### PR TITLE
gmodeler: fix python export - main() 

### PR DESCRIPTION
**Pull request by landam**
In exported Python script from GRASS modeler the `main()` is assumed to be called with two arguments (options, flags).

```
Traceback (most recent call last):
  File "/home/user/grassdata/jena-
region/PERMANENT/.tmp/b802/30427.0", line 34, in <module>
    sys.exit(main())
TypeError: main() missing 2 required positional arguments:
'options' and 'flags'
```

### CODE REVIEW

**Comment by landam** [comment]
Apparently introduced in https://github.com/OSGeo/grass/commit/59f7d9760ec5367562b99b20901f2d00042b679c#diff-f61d660d12caee7d7f6f9db0c8d02267
