### PR TITLE
wxGUI/nviz: fix imports

### LINKED ISSUE #4580: [Bug] cannot import name 'UNCHECKED' from 'ctypes'
## Describe the bug
Upon start the following message is shown on the GUI console:
```
3D view mode not available                                                      
Reason: cannot import name 'UNCHECKED' from 'ctypes' (/usr/lib64/python3.11/ctypes/__init__.py)

```
## To reproduce
1. Start GRASS
2. Check the console

## Expected behavior
Error should not occur

## System description
```
> inxi -S
System:
  Host: localhost.localdomain Kernel: 6.11.3-2-default arch: x86_64 bits: 64
  Desktop: Xfce v: 4.18.1 Distro: openSUSE Tumbleweed 20241022

```
```
System Info                                                                     
GRASS version: 8.5.0dev                                                         
Code revision: 3d7b331ba8                                                       
Build date: 2024-10-24                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.9.2                                                                     
PROJ: 9.5.0                                                                     
GEOS: 3.13.0                                                                    
SQLite: 3.46.0                                                                  
Python: 3.11.10                                                                 
wxPython: 4.2.2                                                                 
Platform: Linux-6.11.3-2-default-x86_64-with-glibc2.40                          
```

### PR DESCRIPTION
**Pull request by petrasovaa**
Fixes #4580 introduced in #4567. Imports were from wrong files. There are still some issues with nviz, but that might be due to some other changes I need to investigate.

### CODE REVIEW

File: gui/wxpython/nviz/wxnviz.py [hunk 1]
```diff
@@ -2443,3 +2448,16 @@ def GetCmd(self):
...
+    "DM_FLAT",
+    "DM_GOURAUD",
+    "DRAW_QUICK_SURFACE",
+    "DRAW_QUICK_VLINES",
+    "DRAW_QUICK_VOLUME",
+    "DRAW_QUICK_VPOINTS",
+    "MAX_ISOSURFS",
+    "ImageTexture",
+    "Nviz",
+]
```
Comment (echoix) [inline gui/wxpython/nviz/wxnviz.py:2463]: As a general guidance, what guided your choices to select what we want to expose to star imports when using from imports of that file?

**Review by echoix — APPROVED** [review]

File: gui/wxpython/nviz/wxnviz.py (hunk 1 above)
Comment (petrasovaa) [reply gui/wxpython/nviz/wxnviz.py:2463]: No "general guidance" here I am afraid, these  are objects imported in wxnviz that are used in other files, this was solving imported but unused.
