### PR TITLE
grass.temporal: fix regression in printing metadata

### LINKED ISSUE #4182: [Bug] t.info fails for single registered raster
## Describe the bug
Printing metadata for raster registered in temporal database fails:
```
t.info type=raster input=lst_2014.005_avg
```

```
 +-------------------- Raster Dataset ----------------------------------------+
 |                                                                            |
 +-------------------- Basic information -------------------------------------+
 | Id: ........................ lst_2014.005_avg@italy_LST_daily
 | Name: ...................... lst_2014.005_avg
 | Mapset: .................... italy_LST_daily
 | Creator: ................... mundialis
 | Temporal type: ............. absolute
 | Creation time: ............. 2019-09-05 12:57:57
 +-------------------- Absolute time -----------------------------------------+
 | Start time:................. 2014-01-05 00:00:00
 | End time:................... 2014-01-06 00:00:00
 +-------------------- Spatial extent ----------------------------------------+
 | North:...................... 2666000.0
 | South:...................... 2228000.0
 | East:.. .................... 4635000.0
 | West:....................... 4053000.0
 | Top:........................ 0.0
 | Bottom:..................... 0.0
Traceback (most recent call last):
  File "/home/akratoc/dev/grass/grass_main/dist.x86_64-pc-linux-gnu/scripts/t.info", line 134, in <module>
    main()
  File "/home/akratoc/dev/grass/grass_main/dist.x86_64-pc-linux-gnu/scripts/t.info", line 129, in main
    dataset.print_info()
  File "/home/akratoc/dev/grass/grass_main/dist.x86_64-pc-linux-gnu/etc/python/grass/temporal/abstract_map_dataset.py", line 308, in print_info
    self.metadata.print_info()
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'RasterMetadata' object has no attribute 'print_info'
```

## Expected behavior
Metadata should work not only for STDS, but also for registered maps.

## Additional context
Broken in 7df1a7e.

### PR DESCRIPTION
**Pull request by petrasovaa**
Fixes #4182 (t.info fails for single registered raster). I tried to work with the current design, although it might have been just easier to revert 7df1a7e, the method inheritance doesn't work very well there.

Besides the reported error, `STDSMetadataBase.print_info()` was also failing. I tested it with the currently deactivated doctests (there are issue running the doctests unrelated to this).

### CODE REVIEW

**Review by ninsbl — APPROVED** [review]
Looks good in general.

The one comment is probably a leftover and can be removed?

You may consider using just one print statement and multile f-strings in the print function. That would be minimally faster and less code, but that is not essential, I guess...

**Comment by petrasovaa** [comment]
> Looks good in general.
> 
> The one comment is probably a leftover and can be removed?
> 
> You may consider using just one print statement and multile f-strings in the print function. That would be minimally faster and less code, but that is not essential, I guess...

Right, but probably out of scope of this PR, there are many places in there that would have to be changed.

**Review by ninsbl — APPROVED** [review]

**Review by veroandreo — APPROVED** [review]
Works as expected now! Thanks!

**Comment by echoix** [comment]
Before merging, can we rerun with main merged here, as tests on Windows are more strict now

**Comment by veroandreo** [comment]
> Before merging, can we rerun with main merged here, as tests on Windows are more strict now

Seems I clicked merge while you were typing this? ops... It was all green ;-)

**Comment by echoix** [comment]
Ya, once I saw the email I looked at it and was writing. It was all green from 60 commits behind main. We'll see how it goes, maybe it'll need a follow-up or not. We'll have our answer in an hour or so

**Comment by echoix** [comment]
So yes, there are some unexpected successes, as some new tests are passing. If the affected tests were solved by this PR (not an unintended side-effect that we would want to be signalled), we need to remove the xfail_windows decorator on these tests.

**Comment by wenzeslaus** [comment]
> ...It was all green...

The choice is between requiring the updated branch before merging (resulting in more CI wait time) or need to judge case-by-case if update is needed with occasional failed runs on main (current state).

**Comment by neteler** [comment]
Can I backport this or anything needed first in G84?
