### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by hjaekel** [OSGeo/grass#3112]
**Describe the bug**
In Grass 8.3.0, when saving the GUI Settings, I get the following Python error:

```
  File "/usr/lib/grass83/gui/wxpython/gui_core/preferences.py", line 1856, in _updateSettings

if (not mapdisp.IsDockable() or not mapdisp.IsDocked()) and
(
^
AttributeError: 'MapPanel' object has no attribute 'IsDockable'. Did you mean: 'IsFocusable'?
```

**To Reproduce**

1. Open Grass
2. In the menu bar, goto Settings → Preferences
3. Click Save

**Expected behavior**
`wx.Panel` has no property `IsDockable`, that property is available in `AuiPaneInfo`.

**System description (please complete the following information):**

- Operating System: Alpine Linux Edge
- GRASS GIS version 8.3.0

```
GRASS > g.version -rge
version=8.3.0
date=2023
revision=exported
build_date=2023-08-03
build_platform=x86_64-alpine-linux-musl
build_off_t_size=8
libgis_revision=8.3.0
libgis_date=2023-08-03T20:16:12+00:00
proj=9.2.1
gdal=3.7.1
geos=3.12.0
sqlite=3.42.0
```

```
~ $ python3 -c "import sys, wx; print(sys.version); print(wx.version())"
3.11.4 (main, Jul 27 2023, 21:07:43) [GCC 13.1.1 20230722]
4.2.0 gtk3 (phoenix) wxWidgets 3.2.2.1
```

**Additional context**
The code was introduced with #3024

**Comment by petrasovaa** [comment]
Thanks for reporting the issue. A workaround is to uncheck "Save current window layout as default" in settings, or install development version, which doesn't have this issue.

**Comment by hjaekel** [comment]
I tested your patch, the issue is fixed.

Thank you!
