### ISSUE TITLE
[Bug] v.hull fails to compile in GRASS 7.8.5

### ISSUE THREAD

**Issue by saultdon** [OSGeo/grass#1563]
**Describe the bug**
When compiling GRASS 7.8.4 against GDAL 3.3.0 the v.hull module fails.

**To Reproduce**
```
GRASS GIS 7.8.5 exported compilation log
--------------------------------------------------
Started compilation: Mon 03 May 2021 10:51:18 PM MST
--
Errors in:
/tmp/makepkg/grass/src/grass-7.8.5/vector/v.hull
```

and the error from the v.hull folder in the src package gives:

```
grass/src/grass-7.8.5/vector/v.hull % make
gcc -D_FORTIFY_SOURCE=2 -march=native -O2 -pipe -fstack-protector-strong -fno-plt   -I/tmp/makepkg/grass/src/grass-7.8.5/dist.x86_64-pc-linux-gnu/include -I/tmp/makepkg/grass/src/grass-7.8.5/dist.x86_64-pc-linux-gnu/include   -I/usr/include -I/usr/include -DPACKAGE=\""grassmods"\"   -I/tmp/makepkg/grass/src/grass-7.8.5/dist.x86_64-pc-linux-gnu/include -I/tmp/makepkg/grass/src/grass-7.8.5/dist.x86_64-pc-linux-gnu/include -DRELDIR=\"vector/v.hull\" -o OBJ.x86_64-pc-linux-gnu/chull.o -c chull.c
In file included from /usr/include/ogr_api.h:47,
                 from /tmp/makepkg/grass/src/grass-7.8.5/dist.x86_64-pc-linux-gnu/include/grass/vect/dig_structs.h:27,
                 from /tmp/makepkg/grass/src/grass-7.8.5/dist.x86_64-pc-linux-gnu/include/grass/vect/digit.h:3,
                 from /tmp/makepkg/grass/src/grass-7.8.5/dist.x86_64-pc-linux-gnu/include/grass/vector.h:4,
                 from chull.c:27:
chull.c:34:19: error: expected ‘;’, identifier or ‘(’ before ‘_Bool’
   34 | { BFALSE, BTRUE } bool;
      |                   ^~~~
make: *** [../../include/Make/Compile.make:32: OBJ.x86_64-pc-linux-gnu/chull.o] Error 1
```

**System description (please complete the following information):**

- Operating System: Arch Linux (5.11.6 kernel)
- GRASS GIS 7.8.4
- GDAL 3.3.0

**Additional context**
Downgrading GDAL to 3.2.2 lets GRASS 7.8.4 compile.

**Comment by neteler** [comment]
The code in question is

```
/*Define Boolean type */
typedef enum
{ BFALSE, BTRUE } bool;
```

https://github.com/OSGeo/grass/blob/55ba3297f6c72f6c6ecf1af78f24c8670ba14a5b/vector/v.hull/chull.c#L33

but I don't see any connection to GDAL so far...

**Comment by saultdon** [comment]
I updated the title so it's not specific - cause I really don't know the cause of the underlying issue.

Not a coder but is it just missing a comma?
```
/*Define Boolean type */
typedef enum
{ BFALSE, BTRUE, } bool;
```

**Comment by nilason** [comment]
`bool` is a C99 addition, which actually needs `#include <stdbool.h>` (but perhaps some compilers are too generous, thus the `_Bool` in the error message) . Testing this I could only reproduce the reported error (using clang) by explicitly include the stdbool.h, which isn't included in `chull.c` at least. Now, there shouldn't be any reason anymore to (re-)typedef a local bool type. The code in chull.c should probably be modified to use standard C bool type, alternatively use the TRUE and FALSE defined in gis.h.
But I'm curious which compiler and version caused this reported error, @saultdon ?

**Comment by neteler** [comment]
Do we want this fixed in the upcoming 7.8.6 release or no hurry?

**Comment by saultdon** [comment]
If it matters too, in the PKGBUILD[1] there is a line that exports CPP as:

```
  # Ancient autoconf used upstream can't handle CPPFLAGS correctly, so set CPP to ignore warnings
  CPP="gcc -E -w" \
```

I'll get you the compiler version today when I get back home (out on the trapline right now with sketchy service).

[1]  https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=grass

**Comment by saultdon** [comment]
I have GCC 10.2.0

**Comment by nilason** [comment]
Thanks for the additional info @saultdon!

> `bool` is a C99 addition, which actually needs `#include <stdbool.h>`

`bool` is a macro for `_Bool` and the use of bool needs the inclusion of stdbool.h for compiling **C** code. This is a deliberate design for C99 to avoid problems (conflicts with legacy/existing code which may have defined a local `bool`) for example with this case of chull.h. However, compiling this code as **C++** (which has `bool` as a built-in type) re-produces exactly the problem reported.
Although the GRASS code *may* be updated to use the C99 bool type, that is not really a fix for this reported issue, which is most likely caused by compiling the C code as C++ code.

E.g. use of locally defined bool (as in chull.c):
works with `clang -x c ...` 
fails with `clang -x c++ ...`

I would suggest that this is a downstream/packaging issue, nothing that should promptly be addressed in GRASS.

**Comment by nilason** [comment]
Now I see where this conflict originates. It is indeed GDAL 3.3.0 related, as [ogr_api.h](https://github.com/OSGeo/gdal/blob/eeeffe624996518655f231125712582551222932/gdal/ogr/ogr_api.h#L47) now includes the `stdbool.h`. 

This will indeed become a general problem the moment GDAL 3.3 will be more widely spread, which may be sooner than later, and should be addressed in GRASS.

**Comment by nilason** [comment]
@saultdon If you can, please test the proposed fix #1567 against GDAL 3.3. It builds fine on GDAL 3.2, but I have no 3.3 around at the moment.

**Comment by saultdon** [comment]
Build works with patch against GDAL 3.3.0

```
% gdalinfo --version
GDAL 3.3.0, released 2021/04/26
```

**Comment by david-geiger** [comment]
Also confirmed hare on Mageia Cauldron #1567 fixes build with gdal 3.3.0.
